
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author natsu
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtCad = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        rbtn2 = new javax.swing.JRadioButton();
        rbtn6 = new javax.swing.JRadioButton();
        rbtn10 = new javax.swing.JRadioButton();
        rbtn14 = new javax.swing.JRadioButton();
        rbtn18 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 565, 49));

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 423, 55));

        buttonGroup1.add(rbtn2);
        rbtn2.setSelected(true);
        rbtn2.setText("Automata 2");
        getContentPane().add(rbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, -1, -1));

        buttonGroup1.add(rbtn6);
        rbtn6.setText("Automata 6");
        getContentPane().add(rbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 90, -1, -1));

        buttonGroup1.add(rbtn10);
        rbtn10.setText("Automata 10");
        getContentPane().add(rbtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 90, -1, -1));

        buttonGroup1.add(rbtn14);
        rbtn14.setText("Automata 14");
        getContentPane().add(rbtn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 90, -1, -1));

        buttonGroup1.add(rbtn18);
        rbtn18.setText("Automata 18");
        getContentPane().add(rbtn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
        elegir();
        automata.verificar();
        if (automata.evaluar(txtCad.getText())) {
            JOptionPane.showMessageDialog(this, "Cadena Aceptada", "Aceptada", WIDTH);
        }else{
            JOptionPane.showMessageDialog(this, "Cadena no Aceptada", "No Aceptada", WIDTH);
        }
        
    }//GEN-LAST:event_btnValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    Automata automata;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rbtn10;
    private javax.swing.JRadioButton rbtn14;
    private javax.swing.JRadioButton rbtn18;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JRadioButton rbtn6;
    private javax.swing.JTextField txtCad;
    // End of variables declaration//GEN-END:variables

public void elegir(){
    if (rbtn2.isSelected()) {
        try {
            File arch = new File("C:\\Users\\SourceMan\\Documents\\ISC\\Automatas\\Automata2.atm");
            FileInputStream r = new FileInputStream(arch);
            ObjectInputStream reader = new ObjectInputStream(r);
            automata = (Automata) reader.readObject();
            reader.close();
            r.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", WIDTH);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al convertir los datos", "Error", WIDTH);
        }
    }
    if (rbtn6.isSelected()) {
        try {
            File arch = new File("C:\\Users\\SourceMan\\Documents\\ISC\\Automatas\\Automata6.atm");
            FileInputStream r = new FileInputStream(arch);
            ObjectInputStream reader = new ObjectInputStream(r);
            automata = (Automata) reader.readObject();
            reader.close();
            r.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", WIDTH);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al convertir los datos", "Error", WIDTH);
        }
    }
    if (rbtn10.isSelected()) {
        try {
            File arch = new File("C:\\Users\\SourceMan\\Documents\\ISC\\Automatas\\Automata10.atm");
            FileInputStream r = new FileInputStream(arch);
            ObjectInputStream reader = new ObjectInputStream(r);
            automata = (Automata) reader.readObject();
            reader.close();
            r.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", WIDTH);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al convertir los datos", "Error", WIDTH);
        }
    }
    if (rbtn14.isSelected()) {
        try {
            File arch = new File("C:\\Users\\SourceMan\\Documents\\ISC\\Automatas\\Automata14.atm");
            FileInputStream r = new FileInputStream(arch);
            ObjectInputStream reader = new ObjectInputStream(r);
            automata = (Automata) reader.readObject();
            reader.close();
            r.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", WIDTH);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al convertir los datos", "Error", WIDTH);
        }
    }
    if (rbtn18.isSelected()) {
        try {
            File arch = new File("C:\\Users\\SourceMan\\Documents\\ISC\\Automatas\\Automata18.atm");
            FileInputStream r = new FileInputStream(arch);
            ObjectInputStream reader = new ObjectInputStream(r);
            automata = (Automata) reader.readObject();
            reader.close();
            r.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", WIDTH);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al convertir los datos", "Error", WIDTH);
        }
    }
}


}
